/**
 * Created by cp on 1/6/14.
 */
module.exports = {
    VIRTUAL_NUMBER:{
        EXP_TIME:10,
        AVA_TIME:5,
        DIAL_COUNT:-1   //通话次数
    },
    LAO_WU_ORDER_TIME:60000,
    TYPE:{
        Gynecology:1,
        Pediatrics:0
    },
    TYPE_NAME:['儿科','产科'],
    USER:{
        User:"user",
        Doctor:"doctor",
        Service:"service",
        Worker:"worker"
    },
    PushMessage:{
        findDoctorOrderGenerate:"onOrderGeneratePush"
    }
    ,
    ORDER_STATUS:{
        DidNotPay:1,
        NotAccept:2,
        Accepted:3,
        NoComment:4,
        Finished:5
    },
    Registration_ORDER_STATUS:{
        NotDispose:0,
        Refuse:1,
        Accepted:2,
        NoComment:3,
        Finished:4,
        TimeOver:5
    },
    SERVICE_ORDER_STATUS:{
        NoComment:0,
        Finished:1
    },
    Registration_TYPE:{
        Normal:1,
        Expert:2,
        Special:3
    },
    ORDER_TYPE:{
        OrderDoctor:"OrderDoctor",
        OrderService:"OrderService",
        OrderWork:"OrderWork"
    },
    ERROR:{
        USER_NOT_LOGIN:{
            code:101,
            message:'用户没有登录'
        },
        USER_NOT_REGISTER:{
            code:102,
            message:'用户没有注册'
        },
        USERNAME_HAS_ALREADY_BEEN_REGISTERED:{
            code:103,
            message:"用户名已经被注册"
        },
        BAD_PASSWORD:{
            code:104,
            message:"密码错误"
        },
        LOGIN_ON_OTHER:{
            code:105,
            message:"下线通知，帐号在其他地方登录!"
        },
        MONEY_NOT_ENOUGH:{
            code:201,
            message:"钱币不够"
        },
        NO_DOCTOR_ONLINE:{
            code:202,
            message:"当前没有医生在线"
        },
        ORDER_IS_ACCEPTED:{
            code:203,
            message:"订单已经被其他医生抢到"
        },
        ORDER_NULL:{
            code:204,
            message:"订单错误或订单ID错误或为空)"
        },
        BAD_ORDER_TYPE:{
            code:205,
            message:"订单类型错误"
        },
        BAD_COMMENT:{
            code:206,
            message:"评价为空"
        },
        NO_WORKER_ONLINE:{
            code:207,
            message:"没有劳务人员在线"
        },
        HAVE_ONT_FINISHED_ORDER:{
            code:208,
            message:"有未完成订单"
        },
        ORDER_OVER_UDE:{
            code:209,
            message:"接受订单超时"
        },
        ORDER_CANT_COMMENT:{
            code:210,
            message:"订单不允许评价"
        },
        ORDER_CANT_PAY:{
            code:211,
            message:"订单不允许支付"
        },
        BAD_USER_TYPE:{
            code:301,
            message:"用户类型错误"
        },
        MISSING_PARAMS:{
            code:302,
            message:"缺失参数"
        }
    },
    ORDER_TYPE_ID:{
        OrderDoctor:1,
        OrderService:2,
        OrderWork:3
    },
    ORDER_TABLE:{
        1:'order_find_doctor',
        2:'order_service',
        3:'order_registration'
    },

    CREDITS:[0,5,20,50],
    POST_URL:{
        '/hangup':1,
        '/recordFileDownload':2
    }

}